# Generated by Django 3.0 on 2019-12-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('trial_ends', models.DateTimeField(auto_created=True, editable=False)),
                ('trial_started', models.DateTimeField(auto_created=True, editable=False)),
                ('created_at', models.DateTimeField(auto_created=True, editable=False)),
                ('miousify_domain_name', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('service_id', models.CharField(editable=False, max_length=40)),
                ('plan', models.CharField(editable=False, max_length=10)),
                ('is_trial', models.BooleanField()),
                ('is_running', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=10)),
                ('instances', models.CharField(max_length=10)),
                ('ram_limit', models.IntegerField()),
                ('storage_capacity', models.IntegerField()),
            ],
        ),
    ]
